# Generated by Django 4.1.4 on 2023-01-09 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0002_enemy_crit_chance_enemy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='base_damage',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='hp',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
