# Generated by Django 4.1.3 on 2023-01-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0002_remove_character_userinventory_inventory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
    ]
