# Generated by Django 4.1.4 on 2023-01-10 17:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0002_alter_inventory_item_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(verbose_name=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_inventory', to='idleServerApp.character')), blank=True, null=True, size=None),
        ),
    ]
