# Generated by Django 4.1.4 on 2023-01-09 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0003_rename_arcana_character_arcana_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armoring_xp',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
