# Generated by Django 4.1.4 on 2023-01-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0003_enemy_base_damage_alter_character_hp_alter_enemy_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='location',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
