# Generated by Django 4.1.4 on 2023-01-10 17:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0003_alter_inventory_item_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item_inventory',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
