# Generated by Django 4.1.4 on 2023-01-04 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0003_alter_character_hp_alter_character_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='arcana',
        ),
        migrations.RemoveField(
            model_name='character',
            name='armoring',
        ),
        migrations.RemoveField(
            model_name='character',
            name='attack',
        ),
        migrations.RemoveField(
            model_name='character',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='cooking',
        ),
        migrations.RemoveField(
            model_name='character',
            name='crit_chance',
        ),
        migrations.RemoveField(
            model_name='character',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dodge',
        ),
        migrations.RemoveField(
            model_name='character',
            name='fishing',
        ),
        migrations.RemoveField(
            model_name='character',
            name='harvesting',
        ),
        migrations.RemoveField(
            model_name='character',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='character',
            name='level',
        ),
        migrations.RemoveField(
            model_name='character',
            name='logging',
        ),
        migrations.RemoveField(
            model_name='character',
            name='mining',
        ),
        migrations.RemoveField(
            model_name='character',
            name='smelting',
        ),
        migrations.RemoveField(
            model_name='character',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='user_character',
        ),
        migrations.RemoveField(
            model_name='character',
            name='weapons',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wood_working',
        ),
        migrations.RemoveField(
            model_name='character',
            name='xp',
        ),
    ]
