# Generated by Django 4.1.4 on 2023-01-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0004_character_armoring_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='aranca_xp',
            new_name='arcana_xp',
        ),
    ]
