# Generated by Django 4.1.4 on 2023-01-04 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idleServerApp', '0005_remove_inventory_user_delete_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armor',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Enemy',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='item_ptr',
        ),
        migrations.DeleteModel(
            name='Armor',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
